var products =[{
    "id":0,
    "title":"-- Select Anyone --",
    "price":"",
    "description":"",
    "brand":"",
    "image":"",
},
// SHAHZAIB SAEED T-SHIRTS
{
    "id":1,
    "title":"Dark Green Plain Half Sleeves Men’s Round Neck T-Shirt",
    "price":1249,
    "description":" Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/TS-1.PNG",
},{
    "id":2,
    "title":"Navy Blue Plain Half Sleeves Men’s Round Neck T-Shirt",
    "price":1249,
    "description":" Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/TEE-187 (1).PNG",
},{
    "id":3,
    "title":"Mustard Plain Half Sleeves Men’s Round Neck T-Shirt",
    "price":1249,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/TEE-186 (1) .PNG",
},{
    "id":4,
    "title":"Maroon Plain Half Sleeves Men’s Round Neck T-Shirt",
    "price":1249,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/184 (1).PNG",
},{
    "id":5,
    "title":"Navy Blue Half Sleeves Men’s Round Neck T-Shirt ",
    "price":1249,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/180 (1) .PNG",
},{
    "id":6,
    "title":"Black Plain Half Sleeves Men’s Round Neck T-Shirt ",
    "price":1249,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/black.1.png",
},{
    "id":7,
    "title":"White Plain Half Sleeves Men’s Round Neck T-Shirt ",
    "price":1249,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/white.1.png",
},{
    "id":8,
    "title":"Tea Pink Plain Contrast Tipping Half Sleeves Polo T-Shirt ",
    "price":32999,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/Polo Shah (E).png",
},{
    "id":9,
    "title":"Beige Plain Half Sleeves Men’s Round Neck T-Shirt",
    "price":1429,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/beige .1.png",
},{
    "id":10,
    "title":"Dark Green Plain Contrast Tipping Half Sleeves Polo T-Shirt",
    "price":1249,
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/Polo Shah (TE).png",
},
{
    "id":0,
    "title":"Multi Color Printed Half Sleeves Men’s Dri Fit T-Shirt",
    "price":"1249",
    "description":"Ready to Wear.Plain T-Shir. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/multi .1.png",
},{
    "id":1,
    "title":"Army Green Half Sleeves Men’s Round Neck T-Shirt ",
    "price":179999,
    "description":"Ready to Wear.Plain T-Shirt. Casual Wear .For Summer Season",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/army.1.png",
},
// SHAHZAIB SAEED POLO SHIRTS
{
    "id":2,
    "title":"Orange Contrast Tipping Half Sleeves Cotton Jersey Polo T-Shirt",
    "price":1249,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"All pictures/polo Shah (1).png",
},{
    "id":3,
    "title":"Light Blue Plain Contrast Tipping Half Sleeves Polo T-Shirt ",
    "price":1249,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":" All Pictures/polo Shah (S).png",
},{
    "id":4,
    "title":"Black Classic Half Sleeves Cotton Polo T-ShirtAll Pictures/polo Shah (T).png",
    "price":1249,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/polo Shah (T).png",
},{
    "id":5,
    "title":"Blue Capri Contrast Tipping Half Sleeves Cotton Jersey Polo T-Shirt",
    "price":35499,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":" All Pictures/polo Shah (F).png",
},{
    "id":6,
    "title":"Yellow Plain Contrast Tipping Half Sleeves Polo T-Shirt ",
    "price":1249,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":" All Pictures/polo Shah (FF).png",
},{
    "id":7,
    "title":"Orange Plain Contrast Tipping Half Sleeves Polo T-Shirt ",
    "price":1249,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/Polo Shah (SI).png",
},{
    "id":8,
    "title":" Slushy Green Classic Half Sleeves Cotton Polo T-Shirt",
    "price":1249,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/Polo Shah (SE).png",
},{
    "id":9,
    "title":"Beige Plain Contrast Tipping Half Sleeves Polo T-Shirt",
    "price":20499,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":" All Pictures/Polo Shah (EL).png",
},{
    "id":10,
    "title":"Maroon Plain Contrast Tipping Half Sleeves Polo T-Shirt ",
    "price":16299,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"images/itelVision3-b.jpg",
},
{
    "id":0,
    "title":"Tea Pink Plain Contrast Tipping Half Sleeves Polo T-Shirt",
    "price":"",
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/Polo Shah (E).png",
}

,{
    "id":1,
    "title":"Black Plain Contrast Tipping Half Sleeves Polo T-Shirt",
    "price":179999,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/Polo Shah (N).png",
},{
    "id":2,
    "title":"Dark Green Plain Contrast Tipping Half Sleeves Polo T-Shirt",
    "price":159999,
    "description":"Jersey Fabric.Machine Wash.Three-button placket.Welt-knit collar,Soft & Stretchable",
    "brand":"Shahzaib Saeed",
    "image":"All Pictures/Polo Shah (TE).png",
}]
